# Triangle, pentagonal, and hexagonal numbers are generated by the
# following formulae:
#
# Triangle       Tn=n(n+1)/2      1, 3, 6, 10, 15, ...
# Pentagonal     Pn=n(3n-1)/2     1, 5, 12, 22, 35, ...
# Hexagonal      Hn=n(2n-1)       1, 6, 15, 28, 45, ...
#
# It can be verified that T285 = P165 = H143 = 40755.
# 
# Find the next triangle number that is also pentagonal and hexagonal.

from math import sqrt
from tools import pentagonal_number
from tools import hexagonal_number

pc = 165
hc = 144

while(True):
    p = pentagonal_number(pc)
    h = hexagonal_number(hc)
    if (p == h):
        print p
        break
    
    if (p < h):
        pc += 1
    else:
        hc += 1
